import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Banner } from '../components/Banner';
import Card from '../components/Card';

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log('Banner button has been clicked!');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Stores</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src='/static/hero-image.png'
            width={700}
            height={400}
            alt='Hero image'
          />
        </div>
        <Card
          name='DarkHorse Coffe'
          imgUrl='/static/hero-image.png'
          href='/coffee-store/darkhorse-coffe'
        />
      </main>
    </div>
  );
}
